
[general]
	#Whether polar bears should target seal mobs.
	polarBearsAttackSeals = true
	#Whether to disable certain aspects of the Lava Vision Potion. Enable if issues with shaders persist.
	shadersCompat = false
	#1 out of this number chance for leaves to drop a banana when broken. Fortune is automatically factored in
	#Range: > 0
	bananaChance = 200
	#Whether soul vulture spawns should be restricted solely to the nether fossil structure or to whatever biome is specified in their respective biome config.
	soulVultureSpawnOnFossil = true
	#Whether wild raccoons steal food from chests.
	raccoonStealFromChests = true
	#Whether mimicubes spawns should be restricted solely to the end city structure or to whatever biome is specified in their respective biome config.
	mimicubeSpawnInEndCity = true
	#Whether mimicream can be used to duplicate items.
	mimicreamRepair = true
	#Whether bananas should drop from blocks tagged with #alexsmobs:drops_bananas
	bananasDropFromLeaves = true
	#Whether acacia blossoms should drop from blocks tagged with #alexsmobs:drops_acacia_blossoms
	acaciaBlossomsDropFromLeaves = true
	#Whether lava can be bottled with a right click of a glass bottle.
	lavaBottleEnabled = true
	#Lava Opacity for the Lava Vision Potion.
	#Range: 0.01 ~ 1.0
	lavaVisionOpacity = 0.65
	#Maximum world y-level that blobfish can spawn at
	#Range: 0 ~ 256
	blobfishSpawnHeight = 38
	#Whether spiders should target fly mobs.
	spidersAttackFlies = true
	#Whether all players should get an Animal Dictionary when joining the world for the first time.
	giveBookOnStartup = true
	#Maximum world y-level that cave centipedes can spawn at
	#Range: 0 ~ 256
	caveCentipedeSpawnHeight = 30
	#Blacklist for items that mimicream cannot make a copy of. Ex: "minecraft:stone_sword", "alexsmobs:blood_sprayer"
	mimicreamBlacklist = ["alexsmobs:blood_sprayer"]
	#Whether wolves should target moose mobs.
	wolvesAttackMoose = true

	[general.spawning]
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		boneSerpentSpawnWeight = 1
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		hummingbirdSpawnWeight = 39
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		roadrunnerSpawnRolls = 1
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		lobsterSpawnRolls = 1
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		endergradeSpawnRolls = 0
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		elephantSpawnWeight = 30
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		spectreSpawnWeight = 10
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		endergradeSpawnWeight = 10
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		hammerheadSharkSpawnWeight = 100
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		sealSpawnRolls = 0
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		sunbirdSpawnRolls = 15
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		shoebillSpawnRolls = 0
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		gazelleSpawnRolls = 0
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		sunbirdSpawnWeight = 2
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		raccoonSpawnWeight = 10
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		crocSpawnRolls = 1
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		mimicubeSpawnWeight = 40
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		blobfishSpawnRolls = 0
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		mooseSpawnRolls = 0
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		spectreSpawnRolls = 5
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		caveCentipedeSpawnRolls = 1
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		crowSpawnRolls = 0
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		grizzlyBearSpawnWeight = 2
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		blobfishSpawnWeight = 30
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		elephantSpawnRolls = 0
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		raccoonSpawnRolls = 0
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		caveCentipedeSpawnWeight = 8
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		shoebillSpawnWeight = 10
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		warpedToadSpawnWeight = 80
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		crowSpawnWeight = 10
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		sealSpawnWeight = 30
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		komodoDragonSpawnWeight = 1
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		flySpawnWeight = 3
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		snowLeopardSpawnRolls = 0
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		rattlesnakeSpawnWeight = 12
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		soulVultureSpawnWeight = 30
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		mooseSpawnWeight = 15
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		komodoDragonSpawnRolls = 400
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		crocodileSpawnWeight = 40
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		soulVultureSpawnRolls = 0
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		orcaSpawnRolls = 6
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		capuchinMonkeySpawnWeight = 55
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		boneSeprentSpawnRolls = 400
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		mimicubeSpawnRolls = 10
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		cockroachSpawnRolls = 200
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		cockroachSpawnWeight = 4
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		gazelleSpawnWeight = 40
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		rattlesnakeSpawnRolls = 400
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		gorillaSpawnWeight = 50
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		roadrunnerSpawnWeight = 15
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		flySpawnRolls = 1
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		lobsterSpawnWeight = 7
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		capuchinMonkeySpawnRolls = 10
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		warpedToadSpawnRolls = 10
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		gorillaSpawnRolls = 0
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		snowLeopardSpawnWeight = 20
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		orcaSpawnWeight = 2
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		hummingbirdSpawnRolls = 1
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		grizzlyBearSpawnRolls = 400
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		crimsonMosquitoSpawnRolls = 300
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		hammerheadSharkSpawnRolls = 1
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		crimsonMosquitoSpawnWeight = 30

